# Generated by Django 2.0.6 on 2019-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('realName', models.CharField(max_length=100)),
                ('accountNumber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
